# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

name: "CI"

jobs:
  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    env:
      php_extensions: ctype, dom, fileinfo, hash, intl, mbstring, session, simplexml, tokenizer, xml, pdo, mysqli, gd, zip
      SS_DATABASE_NAME: test_db
      SS_DATABASE_USERNAME: root
      SS_DATABASE_PASSWORD: root
      SS_DATABASE_SERVER: localhost

    services:
      mysql:
        image: "mysql:5.7"
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.SS_DATABASE_PASSWORD }}
          MYSQL_DATABASE: ${{ env.SS_DATABASE_NAME }}
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.php_extensions }}"
          coverage: "xdebug"

      - name: "Start mysql service"
        run: "sudo /etc/init.d/mysql start"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "~/.composer/cache"
          key: "php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install dependencies with composer"
        run: "composer install --no-ansi --no-interaction --no-progress"

      - name: "Run tests with phpunit/phpunit"
        env:
          SS_DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: "vendor/bin/phpunit --coverage-html=build/logs/coverage/html --coverage-xml=build/logs/coverage"

      - name: "Upload code coverage results to CodeCov"
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml # optional
          flags: unittests # optional

      - name: "Run tests with squizlabs/php_codesniffer"
        run: "vendor/bin/phpcs --config-set ignore_warnings_on_exit 1 && vendor/bin/phpcs -s --report=summary --standard=phpcs.xml.dist --extensions=php,inc --ignore=autoload.php --ignore=vendor/ app/src/ app/tests/"
