name: Deployment

on:
  workflow_run:
    workflows: Tests
    branches: master
    types: completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && ${{ github.event_name != 'pull_request' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: musps/action-deployer-php@master
        with:
          args: deploy production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
